[package]
name = "syoolah-signer"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["full"]}
anyhow = "*"
which = "*"
log = "*"
env_logger = "*"
byteorder = "*"
libc = "*"
libhsmd-sys = {git = "https://github.com/cdecker/lightning", branch = "libhsmd-rust" }
